const home=document.querySelector('#home'),gameView=document.querySelector('#gameView'),shopView=document.querySelector('#shopView');
const gameArea=document.querySelector('#gameArea'),scoreEl=document.querySelector('#score'),titleEl=document.querySelector('#gameTitle'),kickerEl=document.querySelector('#gameKicker');
let score=0,currentGame=null,toastTimer,gameWon=false,mistakes=0,coins=Number(localStorage.getItem('pixelPartyCoins')||0),inventory=JSON.parse(localStorage.getItem('pixelPartyInventory')||'{}');
if(!localStorage.getItem('pixelPartyTestGrant2000')){coins+=2000;localStorage.setItem('pixelPartyCoins',coins);localStorage.setItem('pixelPartyTestGrant2000','1')}
if(!localStorage.getItem('pixelPartyTestPassGrant')){inventory.shuffle=1;inventory.remove=1;inventory.clue=1;localStorage.setItem('pixelPartyInventory',JSON.stringify(inventory));localStorage.setItem('pixelPartyTestPassGrant','1')}
if(!localStorage.getItem('pixelPartyPatternTestKit')){inventory.clue=1;localStorage.setItem('pixelPartyInventory',JSON.stringify(inventory));localStorage.setItem('pixelPartyPatternTestKit','1')}
function saveShop(){localStorage.setItem('pixelPartyCoins',coins);localStorage.setItem('pixelPartyInventory',JSON.stringify(inventory));const el=document.querySelector('#coinCount');if(el)el.textContent=coins}
function openShop(){showView(shopView);saveShop();document.title='Shop | Pixel Party'}
function buyItem(item,cost){if((inventory[item]||0)>0){toast('YOU ALREADY OWN THIS ONE-USE ITEM');return}if(coins<cost){toast(`YOU NEED ${cost-coins} MORE COINS`);return}coins-=cost;inventory[item]=1;if(item==='clue'){localStorage.setItem('patternPowerupReady','1');localStorage.setItem('pixelPartyPatternTestKit','1')}saveShop();toast('ITEM PURCHASED — USE IT IN ITS GAME')}
document.querySelector('#shopButton')?.addEventListener('click',openShop);document.querySelectorAll('.shop-buy').forEach(btn=>btn.onclick=()=>buyItem(btn.dataset.item,{shuffle:500,remove:650,clue:800}[btn.dataset.item]));saveShop();

const games={
  merge:{title:'WORD WEAVER',kicker:'GAME 01 / WORD BUILDING',start:startMerge},
  multiples:{title:'MULTIPLE HUNTER',kicker:'GAME 02 / NUMBER SENSE',start:startMultiples},
  pattern:{title:'PATTERN PULSE',kicker:'GAME 03 / LOGIC',start:startPattern}
};
document.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>openGame(btn.dataset.game)));
document.querySelectorAll('[data-home]').forEach(btn=>btn.addEventListener('click',()=>goHome()));
function showView(view){[home,gameView,shopView].forEach(v=>v?.classList.remove('active'));view.classList.add('active');window.scrollTo(0,0)}
function setRoute(key,value,replace=false){const url=new URL(window.location.href);url.search='';url.hash=value?`#${value}`:'';history[replace?'replaceState':'pushState']({},'',url)}
function openGame(id,updateUrl=true){if(!games[id])return goHome(updateUrl);document.querySelector('.victory-overlay')?.remove();if(updateUrl)setRoute('game',id);document.title=`${games[id].title} | Pixel Party`;currentGame=id;score=0;mistakes=0;gameWon=false;updateScore();showView(gameView);titleEl.textContent=games[id].title;kickerEl.textContent=games[id].kicker;renderMistakes();games[id].start()}
function goHome(updateUrl=true){if(updateUrl)setRoute();document.title='Pixel Party';currentGame=null;gameArea.innerHTML='';showView(home)}
function loadRoute(){const game=window.location.hash.replace('#','')||new URLSearchParams(window.location.search).get('game');if(games[game])openGame(game,false);else goHome(false)}
window.addEventListener('popstate',loadRoute);
window.addEventListener('hashchange',loadRoute);
function updateScore(){scoreEl.textContent=score;if(score>0){coins+=10;saveShop()}}
function earnCoins(amount){coins+=amount;saveShop()}
function renderMistakes(){let el=document.querySelector('#mistakes');if(!el){el=document.createElement('div');el.id='mistakes';el.className='mistakes';document.querySelector('.game-header')?.appendChild(el)}el.innerHTML=Array.from({length:3},(_,i)=>`<span class="mistake-x ${i<mistakes?'lit':''}">×</span>`).join('')}
function registerMistake(){mistakes++;renderMistakes();if(mistakes>=3){setTimeout(()=>showLose(),250);return true}return false}
function showLose(){if(gameWon)return;const lostGame=currentGame,lostWord=lostGame==='merge'?mergeTarget:'';gameWon=true;currentGame=null;document.body.insertAdjacentHTML('beforeend',`<div class="victory-overlay lose-overlay"><section class="victory-bubble"><span class="victory-kicker">RUN OVER</span><h2>YOU LOSE!</h2><p>You used all three mistakes. ${lostWord?`The word was <strong>${lostWord.toUpperCase()}</strong>. `:''}Try again or return to the game room.</p><div class="victory-actions"><button id="closeLose">TRY AGAIN</button><button id="loseHome">GAME ROOM</button></div></section></div>`);document.querySelector('#closeLose').onclick=()=>{document.querySelector('.lose-overlay')?.remove();openGame(lostGame||'merge')};document.querySelector('#loseHome').onclick=()=>{document.querySelector('.lose-overlay')?.remove();goHome()}}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
function shell(instruction,body){gameArea.innerHTML=`<div class="game-shell"><div class="instructions"><b>i</b><span>${instruction}</span></div>${body}</div>`;let strikes=document.querySelector('#mistakes');if(!strikes){renderMistakes();strikes=document.querySelector('#mistakes')}if(strikes)document.querySelector('.game-shell').prepend(strikes);if(currentGame==='merge'){const board=document.querySelector('.merge-board'),candidate=builtWord();board?.insertAdjacentHTML('beforebegin',`<div class="word-slots" aria-label="Word progress">${[...mergeTarget].map((letter,i)=>`<span class="word-slot ${mergeHinted.includes(i)?'hinted':''}">${mergeHinted.includes(i)?mergeTarget[i]:(candidate[i]||'_')}</span>`).join('')}</div>`)}if(currentGame==='merge'&&inventory.shuffle){const actions=document.querySelector('.word-actions');actions?.insertAdjacentHTML('beforeend','<button class="primary" id="shuffleLetters">SHUFFLE TILES</button>');document.querySelector('#shuffleLetters').onclick=()=>{mergeBoard=shuffleWords(mergeBoard);inventory.shuffle=0;saveShop();renderMerge()}}if(currentGame==='multiples'&&inventory.remove){const actions=document.querySelector('#checkMultiples')?.parentElement;actions?.insertAdjacentHTML('beforeend','<button class="primary" id="removeWrong">REMOVE 3 WRONG</button>');document.querySelector('#removeWrong').onclick=()=>{const wrong=[...document.querySelectorAll('[data-num]')].filter(b=>Number(b.textContent)%multipleTarget!==0).slice(0,3);wrong.forEach(b=>b.remove());inventory.remove=0;saveShop()}}if(currentGame==='pattern'&&inventory.clue){const seq=document.querySelector('.pattern-sequence');seq?.insertAdjacentHTML('beforebegin',`<p class="powerup-clue">CLUE: ${buildPattern(patternLevel).slice(0,Math.max(1,Math.floor(patternLevel/4))).map(t=>t.shape).join(' → ')}</p>`);inventory.clue=0;saveShop()}}
function showVictory(gameName,achievement,details=''){
  if(gameWon)return;gameWon=true;currentGame=null;
  const colors=['#eaf238','#ff6534','#5e80ff','#9be073','#f4f0e7'];
  const confetti=Array.from({length:55},(_,i)=>`<i class="confetti-piece" style="left:${(i*37)%100}%;--delay:-${(i%12)*.23}s;--fall:${2.7+(i%7)*.22}s;--color:${colors[i%colors.length]};--spin:${i*29}deg"></i>`).join('');
  document.body.insertAdjacentHTML('beforeend',`<div class="victory-overlay">${confetti}<section class="victory-bubble" role="dialog" aria-modal="true" aria-label="You win"><button class="victory-close" id="closeVictory">×</button><span class="victory-kicker">${gameName} COMPLETE</span><h2>YOU WIN!</h2><p>${achievement}</p><div class="victory-stats"><span><small>FINAL SCORE</small><b>${score}</b></span></div><div class="victory-actions"><button id="victoryHome">GAME ROOM</button></div><div class="victory-details" id="victoryDetails">${details||`You conquered ${gameName} with a final score of ${score}.`}</div></section></div>`);
  document.querySelector('#closeVictory').onclick=()=>{document.querySelector('.victory-overlay')?.remove();gameWon=false};
  document.querySelector('#viewVictory')?.remove();
  document.querySelector('#victoryHome').onclick=()=>{document.querySelector('.victory-overlay')?.remove();goHome()};
}

let mergeBoard,selected=[],mergeLongest=0,mergeClue='',mergeTarget='',mergeLevel=1,mergeCompleted=[],mergeHints=0,mergeHinted=[],lastMergeTarget='';
const mergeLengths=[5,7,9,11,13];
const mergeChallenges={
  5:[{word:'apple',clue:'A round fruit that grows on trees'},{word:'brain',clue:'The organ you use to think'},{word:'power',clue:'The ability or strength to do something'},{word:'smile',clue:'A happy expression on your face'},{word:'light',clue:'Brightness that lets you see'},{word:'chair',clue:'A seat with a back'},{word:'cloud',clue:'A white shape floating in the sky'},{word:'dance',clue:'Move to a rhythm'},{word:'flame',clue:'A bright part of a fire'},{word:'green',clue:'A color made by mixing blue and yellow'},{word:'house',clue:'A place where people live'},{word:'ocean',clue:'A huge body of salt water'},{word:'plant',clue:'A living thing that grows in soil'},{word:'stone',clue:'A small piece of rock'},{word:'table',clue:'Furniture with a flat top'}],
  7:[{word:'pattern',clue:'A design or order that repeats'},{word:'science',clue:'Learning how the natural world works'},{word:'mystery',clue:'Something unexplained or difficult to solve'},{word:'journey',clue:'A trip from one place to another'},{word:'picture',clue:'An image or drawing'},{word:'numbers',clue:'Symbols used for counting'},{word:'balance',clue:'An even and steady state'},{word:'library',clue:'A place filled with books'},{word:'summits',clue:'The highest points of mountains'},{word:'rainbow',clue:'Colored arc seen after rain'},{word:'teacher',clue:'A person who helps others learn'},{word:'whisper',clue:'A very quiet way to speak'},{word:'sunrise',clue:'The sun appearing in the morning'},{word:'lantern',clue:'A portable light'}],
  9:[{word:'classroom',clue:'A room where students learn'},{word:'adventure',clue:'An exciting experience or journey'},{word:'blueberry',clue:'A small blue fruit'},{word:'community',clue:'People living or working together'},{word:'discovery',clue:'Finding something for the first time'},{word:'excellent',clue:'Very good or outstanding'},{word:'knowledge',clue:'Information you understand'},{word:'rectangle',clue:'A shape with four right angles'}],
  11:[{word:'imagination',clue:'The ability to form new ideas in your mind'},{word:'celebration',clue:'A special event honoring something'},{word:'environment',clue:'The world around living things'},{word:'connections',clue:'Links between people or things'},{word:'motivations',clue:'Reasons that make you act'},{word:'friendships',clue:'Caring relationships between friends'},{word:'playgrounds',clue:'Outdoor places where children play'}],
  13:[{word:'understanding',clue:'Knowing the meaning of something'},{word:'accessibility',clue:'How easy something is to reach or use'},{word:'extraordinary',clue:'Very unusual or remarkable'},{word:'determination',clue:'The decision to keep trying'},{word:'communication',clue:'Sharing information with others'}]
};
function shuffleWords(items){return [...items].sort(()=>Math.random()-.5)}
function newMergeLevel(){const needed=mergeLengths[mergeLevel-1],choices=mergeChallenges[needed],recent=JSON.parse(localStorage.getItem('pixelPartyRecentWords')||'[]'),available=choices.filter(challenge=>challenge.word!==lastMergeTarget&&!recent.includes(challenge.word)),pool=available.length?available:choices.filter(challenge=>challenge.word!==lastMergeTarget),challenge=pool[Math.floor(Math.random()*pool.length)]||choices[0];recent.push(challenge.word);localStorage.setItem('pixelPartyRecentWords',JSON.stringify(recent.slice(-12)));const decoyLetters=shuffleWords('etaoinshrdlucmfgypwbv'.split(''));mergeTarget=challenge.word;lastMergeTarget=mergeTarget;mergeClue=challenge.clue;mergeBoard=shuffleWords([...mergeTarget,...decoyLetters.slice(0,Math.max(6,Math.min(10,30-mergeTarget.length)))]);selected=[];mergeHinted=[];renderMerge()}
function startMerge(){mergeLevel=1;mergeLongest=0;mergeCompleted=[];mergeHints=0;newMergeLevel()}
function placedLetters(){const queue=selected.map(i=>mergeBoard[i].toLowerCase());return [...mergeTarget].map((letter,i)=>mergeHinted.includes(i)?letter:(queue.shift()||''))}
function builtWord(){return placedLetters().join('')}
function renderMerge(){const candidate=builtWord(),needed=mergeLengths[mergeLevel-1],letterProgress=Math.min(100,Math.round(candidate.length/needed*100)),runProgress=Math.round((mergeLevel-1)/mergeLengths.length*100),freeHints=Math.max(0,3-mergeHints);shell(`Complete five levels by building ${mergeLengths.join(', ')}-letter words. Use the simplified definition to find each word.`,`<div class="game-status"><h3>LEVEL ${mergeLevel} / 5 · FIND THE ${needed}-LETTER WORD</h3><p>HINT: ${mergeClue}</p></div><div class="run-progress"><div class="run-progress-head merge-progress-head"><b>${letterProgress}% OF THIS WORD · ${runProgress}% OF RUN</b></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${letterProgress}%"></div></div></div><div class="merge-board word-board">${mergeBoard.map((letter,i)=>`<button class="tile word-tile filled ${selected.includes(i)?'selected':''}" data-tile="${i}" aria-label="Letter ${letter}">${letter}</button>`).join('')}</div><div class="word-actions"><button class="primary" id="clearWord">CLEAR</button><button class="primary" id="mergeWord">CHECK WORD</button><button class="primary hint-button" id="wordHint">HINTS (${freeHints} REMAINING)</button></div><p class="dictionary-note">CLICK LETTERS OR TYPE · BACKSPACE UNDOES · 3 FREE HINTS PER RUN; EXTRA HINTS COST A STRIKE</p>`);document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=+b.dataset.tile;if(selected.includes(i))selected=selected.filter(x=>x!==i);else selected.push(i);renderMerge()});document.querySelector('#clearWord').onclick=()=>{selected=[];renderMerge()};document.querySelector('#mergeWord').onclick=checkMerge;document.querySelector('#wordHint').onclick=useWordHint}
function useWordHint(){const availablePositions=[...mergeTarget].map((_,i)=>i).filter(i=>!mergeHinted.includes(i));if(!availablePositions.length)return;if(mergeHints>=3&&registerMistake())return;const hintPosition=availablePositions[Math.floor(Math.random()*availablePositions.length)];mergeHinted.push(hintPosition);mergeHints++;toast(mergeHints<=3?'HINT USED':'HINT USED — STRIKE');renderMerge()}
document.addEventListener('keydown',e=>{if(currentGame!=='merge')return;if(e.key==='Enter'){e.preventDefault();checkMerge()}else if(e.key==='Backspace'){e.preventDefault();selected.pop();renderMerge()}else if(e.key==='Escape'){e.preventDefault();selected=[];renderMerge()}else if(/^[a-z]$/i.test(e.key)){e.preventDefault();const letter=e.key.toLowerCase(),i=mergeBoard.findIndex((tile,index)=>tile===letter&&!selected.includes(index));if(i<0)toast(`NO ${letter.toUpperCase()} LETTER AVAILABLE — TRY ANOTHER LETTER OR PRESS BACKSPACE`);else{selected.push(i);renderMerge()}}});
function checkMerge(){const word=builtWord(),needed=mergeLengths[mergeLevel-1];if(!word){toast('SELECT OR TYPE SOME LETTERS FIRST');return}if(word.length!==needed){toast(`THIS LEVEL NEEDS EXACTLY ${needed} LETTERS`);return}if(word!==mergeTarget){toast('NOT THE WORD DESCRIBED BY THE HINT — TRY AGAIN');return}mergeCompleted.push({level:mergeLevel,length:needed,word});mergeLongest=Math.max(mergeLongest,word.length);score+=word.length*10+mergeLevel*25;updateScore();if(mergeLevel>=mergeLengths.length){const completedList=`<h3>LEVELS COMPLETED</h3><ol class="victory-levels">${mergeCompleted.map(item=>`<li><span>LEVEL ${item.level} · ${item.length} LETTERS</span><b>${item.word.toUpperCase()}</b></li>`).join('')}</ol>`;setTimeout(()=>currentGame==='merge'&&showVictory('MERGE MAESTRO',`You cleared all five levels and finished with “${word.toUpperCase()}”!`,completedList),350)}else{mergeLevel++;toast(`CORRECT · LEVEL ${mergeLevel} UNLOCKED`);setTimeout(()=>currentGame==='merge'&&newMergeLevel(),450)}}
// Shared mistake-aware submission for Word Weaver.
function checkMerge(){const word=builtWord(),needed=mergeLengths[mergeLevel-1];if(!word){if(registerMistake())return;toast('SELECT OR TYPE SOME LETTERS FIRST');return}if(word.length!==needed){if(registerMistake())return;toast(`THIS LEVEL NEEDS EXACTLY ${needed} LETTERS`);return}if(word!==mergeTarget){if(registerMistake())return;toast('NOT THE WORD DESCRIBED BY THE HINT — TRY AGAIN');return}mergeCompleted.push({level:mergeLevel,length:needed,word});mergeLongest=Math.max(mergeLongest,word.length);score+=word.length*10+mergeLevel*25;updateScore();if(mergeLevel>=mergeLengths.length){setTimeout(()=>currentGame==='merge'&&showVictory('WORD WEAVER',`You cleared all five levels and finished with “${word.toUpperCase()}”!`),350)}else{mergeLevel++;toast(`CORRECT · LEVEL ${mergeLevel} UNLOCKED`);setTimeout(()=>currentGame==='merge'&&newMergeLevel(),450)}}
let multipleTarget,multipleNums,multipleSelected,multipleStreak=0,multipleLevel=1,multipleHints=0;
function startMultiples(){multipleLevel=1;multipleStreak=0;multipleHints=0;newMultipleRound()}
function newMultipleRound(){const min=2+(multipleLevel-1)*5;multipleTarget=min+Math.floor(Math.random()*8);multipleSelected=[];const factors=shuffleWords([1,2,3,4,5,6,7,8,9,10]).slice(0,4+Math.floor(Math.random()*3));const correct=factors.map(f=>multipleTarget*f);const candidates=[];for(let n=1;n<=multipleTarget*30;n++)if(n%multipleTarget!==0&&!correct.includes(n))candidates.push(n);const decoys=shuffleWords(candidates).slice(0,11);multipleNums=[...correct,...decoys].sort(()=>Math.random()-.5);renderMultiples()}
function renderMultiples(){const progress=multipleLevel*10,neededCount=multipleNums.filter(n=>n%multipleTarget===0).length,freeHints=Math.max(0,3-multipleHints);shell('Clear 10 rounds. Each round uses a larger randomized target.',`<div class="game-status"><div><h3>FIND MULTIPLES OF <span style="color:var(--orange)">${multipleTarget}</span></h3><p>SEARCHING FOR ${neededCount} MULTIPLES</p></div><p>${multipleSelected.length} SELECTED</p></div><div class="run-progress"><div class="run-progress-head"><span>LEVEL ${multipleLevel}</span><b>${progress}% COMPLETE</b><span>LEVEL 10</span></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${progress}%"></div></div></div><div class="number-grid">${multipleNums.map((n,i)=>`<button class="number-choice ${multipleSelected.includes(i)?'selected':''}" data-num="${i}">${n}</button>`).join('')}</div><div style="text-align:center;margin-top:20px"><button id="checkMultiples" class="primary">CHECK PICKS</button><button id="multipleHint" class="primary hint-button">HINTS (${freeHints} REMAINING)</button></div>`);document.querySelectorAll('[data-num]').forEach(b=>b.onclick=()=>{const i=+b.dataset.num;multipleSelected=multipleSelected.includes(i)?multipleSelected.filter(x=>x!==i):[...multipleSelected,i];renderMultiples()});document.querySelector('#checkMultiples').onclick=checkMultiples;document.querySelector('#multipleHint').onclick=useMultipleHint}
function useMultipleHint(){const available=multipleNums.map((n,i)=>n%multipleTarget===0&&!multipleSelected.includes(i)?i:-1).filter(i=>i>=0);if(!available.length)return;if(multipleHints>=3&&registerMistake())return;multipleSelected.push(available[Math.floor(Math.random()*available.length)]);multipleHints++;toast(multipleHints<=3?'HINT USED':'HINT USED — STRIKE');renderMultiples()}
function checkMultiples(){const right=multipleNums.map((n,i)=>n%multipleTarget===0?i:-1).filter(i=>i>=0);const perfect=right.length===multipleSelected.length&&right.every(i=>multipleSelected.includes(i));if(perfect){multipleStreak++;score+=right.length*10+multipleLevel*5;updateScore();if(multipleLevel>=10){setTimeout(()=>currentGame==='multiples'&&showVictory('MULTIPLE HUNTER','You cleared all 10 increasingly difficult hunts!'),400)}else{multipleLevel++;setTimeout(()=>currentGame==='multiples'&&newMultipleRound(),650)}}else{multipleStreak=0;if(registerMistake())return;score=Math.max(0,score-5);updateScore();toast('NOT QUITE — TRY THIS LEVEL AGAIN')}}

let patternLevel=1,patternAnswer,patternOptions=[];
const symbols=['●','▲','■','◆','★','✚'],patternColors=['#151515','#ff6534','#5e80ff','#70b94d','#8c43c7'];
function startPattern(){patternLevel=1;newPattern()}
function patternToken(shape,color='#151515',rotation=0,size=1){return{shape,color,rotation,size}}
function tokenKey(t){return`${t.shape}|${t.color}|${t.rotation}|${t.size}`}
function tokenHTML(t,tag='span',extra='',attrs=''){return`<${tag} class="pattern-symbol ${extra}" ${attrs} style="color:${t.color};transform:rotate(${t.rotation}deg) scale(${t.size})">${t.shape}</${tag}>`}
function buildPattern(level){
  const length=level<=5?5+Math.floor(level/2):level<=10?7+Math.floor((level-6)/2):level<=15?8+Math.floor((level-11)/2):level<=20?9+Math.floor((level-16)/2):11+Math.floor((level-21)/2);
  const a=symbols[level%symbols.length],b=symbols[(level+2)%symbols.length],c=symbols[(level+4)%symbols.length];const seq=[];
  for(let i=0;i<length;i++){
    if(level<=5)seq.push(patternToken(i%2?a:b));
    else if(level<=10)seq.push(patternToken([a,b,c][i%3]));
    else if(level<=15)seq.push(patternToken(i%2?a:b,patternColors[i%3]));
    else if(level<=20)seq.push(patternToken([a,b,c][i%3],patternColors[i%2],(i%4)*45));
    else seq.push(patternToken([a,b,c][i%3],patternColors[(i*2)%patternColors.length],(i%4)*45,i%2?.78:1.05));
  }
  return seq;
}
function makeDistractor(answer,n){return patternToken(symbols[(symbols.indexOf(answer.shape)+n+1)%symbols.length],patternColors[(patternColors.indexOf(answer.color)+n+1+patternColors.length)%patternColors.length],(answer.rotation+(n+1)*45)%360,answer.size===1.05?.78:1.05)}
function newPattern(){const seq=buildPattern(patternLevel);patternAnswer=seq[seq.length-1];const shown=seq.slice(0,-1);const wrongCount=3,progress=patternLevel*4;patternOptions=patternLevel<=10?[patternAnswer,...Array.from({length:wrongCount},(_,i)=>patternToken(symbols[(symbols.indexOf(patternAnswer.shape)+i+1)%symbols.length]))]:[patternAnswer,...Array.from({length:wrongCount},(_,i)=>makeDistractor(patternAnswer,i))];patternOptions.sort(()=>Math.random()-.5);shell('Patterns grow longer and more complex, but only the final shape is missing.',`<div class="game-status"><h3>LEVEL ${patternLevel} / 25</h3><p>WHAT COMES NEXT?</p></div><div class="run-progress"><div class="run-progress-head"><span>LEVEL ${patternLevel}</span><b>${progress}% COMPLETE</b><span>LEVEL 25</span></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${progress}%"></div></div></div><div class="pattern-sequence">${shown.map(x=>tokenHTML(x)).join('')}<span class="pattern-symbol missing">?</span></div><div class="pattern-options">${patternOptions.map((x,i)=>tokenHTML(x,'button','pattern-option-choice',`data-option="${i}"`)).join('')}</div>`);document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>checkPattern(+b.dataset.option))}
function checkPattern(choice){if(tokenKey(patternOptions[choice])===tokenKey(patternAnswer)){const completed=patternLevel;score+=completed*10;updateScore();if(completed>=25){setTimeout(()=>currentGame==='pattern'&&showVictory('PATTERN PULSE','You mastered all 25 visual patterns!'),400)}else{patternLevel++;setTimeout(()=>currentGame==='pattern'&&newPattern(),500)}}else{if(registerMistake())return;score=Math.max(0,score-5);updateScore();toast('LOOK AGAIN — CHECK EVERY PROPERTY')}}

const checkMultiplesWithEmptyGuard=checkMultiples;checkMultiples=function(){if(!multipleSelected.length){toast(`YOU NEED TO SELECT ${multipleNums.filter(n=>n%multipleTarget===0).length} NUMBERS`);return}return checkMultiplesWithEmptyGuard()};
loadRoute();
const wordWeaverRender=renderMerge;
renderMerge=function(){wordWeaverRender();if(currentGame==='merge'){document.querySelectorAll('.word-slot').forEach((slot,i)=>{slot.textContent=placedLetters()[i]||'';slot.classList.toggle('hinted',mergeHinted.includes(i))})}};
function addPowerupBar(){document.querySelector('.powerup-bar')?.remove();const key={merge:'shuffle',multiples:'remove',pattern:'clue'}[currentGame];if(!key)return;const testClue=key==='clue'&&localStorage.getItem('pixelPartyPatternTestKit');const count=inventory[key]|| (testClue?1:0),bar=document.createElement('div');bar.className=`powerup-bar ${count?'available':'empty'}`;bar.innerHTML=`<button class="powerup-use" type="button">USE POWERUP <span>(${count} AVAILABLE)</span></button>`;document.querySelector('.game-shell')?.append(bar);bar.querySelector('button').onclick=()=>{if(!count){toast('NO POWERUP AVAILABLE — VISIT THE SHOP');return}if(key==='pattern'){const seq=document.querySelector('.pattern-sequence');if(seq&&!document.querySelector('.pattern-motif-clue')){const motif=buildPattern(patternLevel).slice(0,Math.min(3,Math.max(2,Math.floor(patternLevel/3))));seq.insertAdjacentHTML('beforebegin',`<div class="pattern-motif-clue">⌒ ${motif.map(t=>t.shape).join(' · ')} REPEATING MOTIF ⌒</div>`);inventory.clue=0;saveShop();if(testClue){inventory.clue=1;saveShop()}addPowerupBar()}return}if(key==='remove'){const wrong=[...document.querySelectorAll('[data-num]')].filter(b=>Number(b.textContent)%multipleTarget!==0).slice(0,3);wrong.forEach(b=>b.remove());inventory.remove=0;saveShop();addPowerupBar();return}document.querySelector('#shuffleLetters')?.click()||toast('POWERUP READY')};}
const originalShell=shell;shell=function(instruction,body){originalShell(instruction,body);addPowerupBar()};addPowerupBar();
addPowerupBar=function(){document.querySelector('.powerup-bar')?.remove();const key={merge:'shuffle',multiples:'remove',pattern:'clue'}[currentGame];if(!key)return;const testClue=key==='clue'&&localStorage.getItem('pixelPartyPatternTestKit'),count=inventory[key]||(testClue?1:0),bar=document.createElement('div');bar.className=`powerup-bar ${count?'available':'empty'}`;bar.innerHTML=`<button class="powerup-use" type="button">USE POWERUP <span>(${count} AVAILABLE)</span></button>`;document.querySelector('.game-shell')?.append(bar);bar.querySelector('button').onclick=()=>{if(!count){toast('NO POWERUP AVAILABLE — VISIT THE SHOP');return}if(key==='pattern'){const seq=document.querySelector('.pattern-sequence');if(!seq){toast('OPEN THE PATTERN BOARD TO USE THIS POWERUP');return}document.querySelector('.pattern-motif-clue')?.remove();const motif=buildPattern(patternLevel).slice(0,3);seq.insertAdjacentHTML('beforebegin',`<div class="pattern-motif-clue">⌒ ${motif.map(t=>t.shape).join(' · ')} REPEATING MOTIF ⌒</div>`);if(!testClue){inventory.clue=0;saveShop()}return}if(key==='remove'){[...document.querySelectorAll('[data-num]')].filter(b=>Number(b.textContent)%multipleTarget!==0).slice(0,3).forEach(b=>b.remove());inventory.remove=0;saveShop();return}document.querySelector('#shuffleLetters')?.click()||toast('POWERUP READY')}};addPowerupBar();
document.addEventListener('click',e=>{if(!e.target.closest('.powerup-use')||currentGame!=='pattern')return;const seq=document.querySelector('.pattern-sequence');if(!seq)return;document.querySelector('.pattern-motif-clue')?.remove();const motif=buildPattern(patternLevel).slice(0,3);seq.insertAdjacentHTML('beforebegin',`<div class="pattern-motif-clue">⌒ ${motif.map(t=>t.shape).join(' · ')} REPEATING MOTIF ⌒</div>`);toast('PATTERN MOTIF REVEALED')});
function showCleanPatternMotif(){const seq=document.querySelector('.pattern-sequence');if(!seq)return;document.querySelectorAll('.motif-bracket').forEach(el=>el.remove());document.querySelector('.pattern-motif-clue')?.remove();const items=[...seq.querySelectorAll('.pattern-symbol')].filter(el=>!el.classList.contains('missing'));if(items.length<4)return;seq.style.position='relative';[0,2].forEach((start,index)=>{const first=items[start],last=items[start+1],bracket=document.createElement('div');bracket.className='motif-bracket';bracket.style.left=`${first.offsetLeft-7}px`;bracket.style.width=`${last.offsetLeft+last.offsetWidth-first.offsetLeft+14}px`;bracket.innerHTML=`<span>${index?'NEXT MOTIF':'REPEATING MOTIF'}</span>`;seq.append(bracket)})}
document.addEventListener('click',e=>{if(e.target.closest('.powerup-use')&&currentGame==='pattern'){setTimeout(showCleanPatternMotif,0)}});
document.addEventListener('click',e=>{if(!e.target.closest('.powerup-use'))return;setTimeout(()=>{const key={merge:'shuffle',multiples:'remove',pattern:'clue'}[currentGame];if(key){inventory[key]=0;if(key==='clue')localStorage.removeItem('pixelPartyPatternTestKit');saveShop();addPowerupBar()}},25)});
