const home=document.querySelector('#home'),gameView=document.querySelector('#gameView');
const gameArea=document.querySelector('#gameArea'),scoreEl=document.querySelector('#score'),titleEl=document.querySelector('#gameTitle'),kickerEl=document.querySelector('#gameKicker');
let score=0,currentGame=null,toastTimer,gameWon=false,mistakes=0;

const games={
  merge:{title:'WORD WEAVER',kicker:'GAME 01 / WORD BUILDING',start:startMerge},
  multiples:{title:'MULTIPLE HUNTER',kicker:'GAME 02 / NUMBER SENSE',start:startMultiples},
  pattern:{title:'PATTERN PULSE',kicker:'GAME 03 / LOGIC',start:startPattern}
};
document.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>openGame(btn.dataset.game)));
document.querySelectorAll('[data-home]').forEach(btn=>btn.addEventListener('click',()=>goHome()));
function showView(view){[home,gameView].forEach(v=>v.classList.remove('active'));view.classList.add('active');window.scrollTo(0,0)}
function setRoute(key,value,replace=false){const url=new URL(window.location.href);url.search='';url.hash='';if(key&&value)url.searchParams.set(key,value);history[replace?'replaceState':'pushState']({},'',url)}
function openGame(id,updateUrl=true){if(!games[id])return goHome(updateUrl);document.querySelector('.victory-overlay')?.remove();if(updateUrl)setRoute('game',id);document.title=`${games[id].title} | Pixel Party`;currentGame=id;score=0;mistakes=0;gameWon=false;updateScore();showView(gameView);titleEl.textContent=games[id].title;kickerEl.textContent=games[id].kicker;renderMistakes();games[id].start()}
function goHome(updateUrl=true){if(updateUrl)setRoute();document.title='Pixel Party';currentGame=null;gameArea.innerHTML='';showView(home)}
function loadRoute(){const params=new URLSearchParams(window.location.search),game=params.get('game');if(games[game])openGame(game,false);else goHome(false)}
window.addEventListener('popstate',loadRoute);
function updateScore(){scoreEl.textContent=score}
function renderMistakes(){let el=document.querySelector('#mistakes');if(!el){el=document.createElement('div');el.id='mistakes';el.className='mistakes';document.querySelector('.game-header')?.appendChild(el)}el.innerHTML=Array.from({length:3},(_,i)=>`<span class="mistake-x ${i<mistakes?'lit':''}">×</span>`).join('')}
function registerMistake(){mistakes++;renderMistakes();if(mistakes>=3){setTimeout(()=>showLose(),250);return true}return false}
function showLose(){if(gameWon)return;const lostGame=currentGame;gameWon=true;currentGame=null;document.body.insertAdjacentHTML('beforeend',`<div class="victory-overlay lose-overlay"><section class="victory-bubble"><span class="victory-kicker">RUN OVER</span><h2>YOU LOSE!</h2><p>You used all three mistakes. Try again or return to the game room.</p><div class="victory-actions"><button id="closeLose">TRY AGAIN</button><button id="loseHome">GAME ROOM</button></div></section></div>`);document.querySelector('#closeLose').onclick=()=>{document.querySelector('.lose-overlay')?.remove();openGame(lostGame||'merge')};document.querySelector('#loseHome').onclick=()=>{document.querySelector('.lose-overlay')?.remove();goHome()}}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
function shell(instruction,body){gameArea.innerHTML=`<div class="game-shell"><div class="instructions"><b>i</b><span>${instruction}</span></div>${body}</div>`;let strikes=document.querySelector('#mistakes');if(!strikes){renderMistakes();strikes=document.querySelector('#mistakes')}if(strikes)document.querySelector('.game-shell').prepend(strikes)}
function showVictory(gameName,achievement,details=''){
  if(gameWon)return;gameWon=true;currentGame=null;
  const colors=['#eaf238','#ff6534','#5e80ff','#9be073','#f4f0e7'];
  const confetti=Array.from({length:55},(_,i)=>`<i class="confetti-piece" style="left:${(i*37)%100}%;--delay:-${(i%12)*.23}s;--fall:${2.7+(i%7)*.22}s;--color:${colors[i%colors.length]};--spin:${i*29}deg"></i>`).join('');
  document.body.insertAdjacentHTML('beforeend',`<div class="victory-overlay">${confetti}<section class="victory-bubble" role="dialog" aria-modal="true" aria-label="You win"><button class="victory-close" id="closeVictory">×</button><span class="victory-kicker">${gameName} COMPLETE</span><h2>YOU WIN!</h2><p>${achievement}</p><div class="victory-stats"><span><small>FINAL SCORE</small><b>${score}</b></span></div><div class="victory-actions"><button id="victoryHome">GAME ROOM</button></div><div class="victory-details" id="victoryDetails">${details||`You conquered ${gameName} with a final score of ${score}.`}</div></section></div>`);
  document.querySelector('#closeVictory').onclick=()=>{document.querySelector('.victory-overlay')?.remove();gameWon=false};
  document.querySelector('#viewVictory')?.remove();
  document.querySelector('#victoryHome').onclick=()=>{document.querySelector('.victory-overlay')?.remove();goHome()};
}

let mergeBoard,selected=[],mergeLongest=0,mergeClue='',mergeTarget='',mergeLevel=1,mergeCompleted=[];
const mergeLengths=[5,7,10,12,15];
const mergeChallenges={
  5:[{word:'apple',clue:'A round fruit that grows on trees'},{word:'brain',clue:'The organ you use to think'},{word:'power',clue:'The ability or strength to do something'},{word:'smile',clue:'A happy expression on your face'}],
  7:[{word:'pattern',clue:'A design or order that repeats'},{word:'science',clue:'Learning how the natural world works'},{word:'mystery',clue:'Something unexplained or difficult to solve'},{word:'journey',clue:'A trip from one place to another'}],
  10:[{word:'basketball',clue:'A sport played by shooting a ball through a hoop'},{word:'friendship',clue:'A caring relationship between friends'},{word:'lighthouse',clue:'A tower with a light that guides ships'},{word:'dictionary',clue:'A book or resource that explains words'}],
  12:[{word:'encyclopedia',clue:'A reference that explains many different subjects'},{word:'relationship',clue:'The way people or things are connected'},{word:'architecture',clue:'The art of designing buildings'},{word:'refrigerator',clue:'A machine that keeps food cold'}],
  15:[{word:'congratulations',clue:'Words used to celebrate someone’s success'},{word:'misapprehension',clue:'A wrong understanding of something'},{word:'characteristics',clue:'Features that describe a person or thing'},{word:'instrumentation',clue:'Tools or equipment used for a particular job'}]
};
function shuffleWords(items){return [...items].sort(()=>Math.random()-.5)}
function newMergeLevel(){const needed=mergeLengths[mergeLevel-1],choices=mergeChallenges[needed],challenge=choices[Math.floor(Math.random()*choices.length)],decoyLetters=shuffleWords('etaoinshrdlucmfgypwbv'.split(''));mergeTarget=challenge.word;mergeClue=challenge.clue;mergeBoard=shuffleWords([...mergeTarget,...decoyLetters.slice(0,Math.max(6,Math.min(10,30-mergeTarget.length)))]);selected=[];renderMerge()}
function startMerge(){mergeLevel=1;mergeLongest=0;mergeCompleted=[];newMergeLevel()}
function builtWord(){return selected.map(i=>mergeBoard[i]).join('').toLowerCase()}
function renderMerge(){const candidate=builtWord(),needed=mergeLengths[mergeLevel-1],letterProgress=Math.min(100,Math.round(candidate.length/needed*100)),runProgress=Math.round((mergeLevel-1)/mergeLengths.length*100);shell(`Complete five levels by building ${mergeLengths.join(', ')}-letter words. Use the simplified definition to find each word.`,`<div class="game-status"><h3>LEVEL ${mergeLevel} / 5 · FIND THE ${needed}-LETTER WORD</h3><p>HINT: ${mergeClue}</p></div><div class="run-progress"><div class="run-progress-head merge-progress-head"><b>${letterProgress}% OF THIS WORD · ${runProgress}% OF RUN</b></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${letterProgress}%"></div></div></div><div class="merge-board word-board">${mergeBoard.map((letter,i)=>`<button class="tile word-tile filled ${selected.includes(i)?'selected':''}" data-tile="${i}" aria-label="Letter ${letter}">${letter}</button>`).join('')}</div><div class="keyboard-answer word-answer"><span>Your word:</span><strong id="typedAnswer">${candidate||'—'}</strong></div><div class="word-actions"><button class="primary" id="clearWord">CLEAR</button><button class="primary" id="mergeWord">CHECK WORD</button></div><p class="dictionary-note">CLICK LETTERS OR TYPE · BACKSPACE UNDOES · ENTER CHECKS · NO LOADING REQUIRED</p>`);document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=+b.dataset.tile;if(selected.includes(i))selected=selected.filter(x=>x!==i);else selected.push(i);renderMerge()});document.querySelector('#clearWord').onclick=()=>{selected=[];renderMerge()};document.querySelector('#mergeWord').onclick=checkMerge}
document.addEventListener('keydown',e=>{if(currentGame!=='merge')return;if(e.key==='Enter'){e.preventDefault();checkMerge()}else if(e.key==='Backspace'){e.preventDefault();selected.pop();renderMerge()}else if(e.key==='Escape'){e.preventDefault();selected=[];renderMerge()}else if(/^[a-z]$/i.test(e.key)){e.preventDefault();const letter=e.key.toLowerCase(),i=mergeBoard.findIndex((tile,index)=>tile===letter&&!selected.includes(index));if(i<0)toast(`NO ${letter.toUpperCase()} LETTER AVAILABLE — TRY ANOTHER LETTER OR PRESS BACKSPACE`);else{selected.push(i);renderMerge()}}});
function checkMerge(){const word=builtWord(),needed=mergeLengths[mergeLevel-1];if(!word){toast('SELECT OR TYPE SOME LETTERS FIRST');return}if(word.length!==needed){toast(`THIS LEVEL NEEDS EXACTLY ${needed} LETTERS`);return}if(word!==mergeTarget){toast('NOT THE WORD DESCRIBED BY THE HINT — TRY AGAIN');return}mergeCompleted.push({level:mergeLevel,length:needed,word});mergeLongest=Math.max(mergeLongest,word.length);score+=word.length*10+mergeLevel*25;updateScore();if(mergeLevel>=mergeLengths.length){const completedList=`<h3>LEVELS COMPLETED</h3><ol class="victory-levels">${mergeCompleted.map(item=>`<li><span>LEVEL ${item.level} · ${item.length} LETTERS</span><b>${item.word.toUpperCase()}</b></li>`).join('')}</ol>`;setTimeout(()=>currentGame==='merge'&&showVictory('MERGE MAESTRO',`You cleared all five levels and finished with “${word.toUpperCase()}”!`,completedList),350)}else{mergeLevel++;toast(`CORRECT · LEVEL ${mergeLevel} UNLOCKED`);setTimeout(()=>currentGame==='merge'&&newMergeLevel(),450)}}
// Shared mistake-aware submission for Word Weaver.
function checkMerge(){const word=builtWord(),needed=mergeLengths[mergeLevel-1];if(!word){if(registerMistake())return;toast('SELECT OR TYPE SOME LETTERS FIRST');return}if(word.length!==needed){if(registerMistake())return;toast(`THIS LEVEL NEEDS EXACTLY ${needed} LETTERS`);return}if(word!==mergeTarget){if(registerMistake())return;toast('NOT THE WORD DESCRIBED BY THE HINT — TRY AGAIN');return}mergeCompleted.push({level:mergeLevel,length:needed,word});mergeLongest=Math.max(mergeLongest,word.length);score+=word.length*10+mergeLevel*25;updateScore();if(mergeLevel>=mergeLengths.length){setTimeout(()=>currentGame==='merge'&&showVictory('WORD WEAVER',`You cleared all five levels and finished with “${word.toUpperCase()}”!`),350)}else{mergeLevel++;toast(`CORRECT · LEVEL ${mergeLevel} UNLOCKED`);setTimeout(()=>currentGame==='merge'&&newMergeLevel(),450)}}
let multipleTarget,multipleNums,multipleSelected,multipleStreak=0,multipleLevel=1;
function startMultiples(){multipleLevel=1;multipleStreak=0;newMultipleRound()}
function newMultipleRound(){const min=2+(multipleLevel-1)*5;multipleTarget=min+Math.floor(Math.random()*8);multipleSelected=[];const factors=shuffleWords([1,2,3,4,5,6,7,8,9,10]).slice(0,4+Math.floor(Math.random()*3));const correct=factors.map(f=>multipleTarget*f);const decoys=[];while(decoys.length<11){const n=Math.max(2,Math.floor(multipleTarget*.6)+Math.floor(Math.random()*multipleTarget*8));if(n%multipleTarget!==0&&!decoys.includes(n)&&!correct.includes(n))decoys.push(n)}multipleNums=[...correct,...decoys].sort(()=>Math.random()-.5);renderMultiples()}
function renderMultiples(){const progress=multipleLevel*10;shell('Clear 10 rounds. Each round uses a larger randomized target.',`<div class="game-status"><h3>FIND MULTIPLES OF <span style="color:var(--orange)">${multipleTarget}</span></h3><p>${multipleSelected.length} SELECTED</p></div><div class="run-progress"><div class="run-progress-head"><span>LEVEL ${multipleLevel}</span><b>${progress}% COMPLETE</b><span>LEVEL 10</span></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${progress}%"></div></div></div><div class="number-grid">${multipleNums.map((n,i)=>`<button class="number-choice ${multipleSelected.includes(i)?'selected':''}" data-num="${i}">${n}</button>`).join('')}</div><div style="text-align:center;margin-top:20px"><button id="checkMultiples" class="primary">CHECK PICKS</button></div>`);document.querySelectorAll('[data-num]').forEach(b=>b.onclick=()=>{const i=+b.dataset.num;multipleSelected=multipleSelected.includes(i)?multipleSelected.filter(x=>x!==i):[...multipleSelected,i];renderMultiples()});document.querySelector('#checkMultiples').onclick=checkMultiples}
function checkMultiples(){const right=multipleNums.map((n,i)=>n%multipleTarget===0?i:-1).filter(i=>i>=0);const perfect=right.length===multipleSelected.length&&right.every(i=>multipleSelected.includes(i));if(perfect){multipleStreak++;score+=right.length*10+multipleLevel*5;updateScore();if(multipleLevel>=10){setTimeout(()=>currentGame==='multiples'&&showVictory('MULTIPLE HUNTER','You cleared all 10 increasingly difficult hunts!'),400)}else{multipleLevel++;setTimeout(()=>currentGame==='multiples'&&newMultipleRound(),650)}}else{multipleStreak=0;if(registerMistake())return;score=Math.max(0,score-5);updateScore();toast('NOT QUITE — TRY THIS LEVEL AGAIN')}}

let patternLevel=1,patternAnswer,patternOptions=[];
const symbols=['●','▲','■','◆','★','✚'],patternColors=['#151515','#ff6534','#5e80ff','#70b94d','#8c43c7'];
function startPattern(){patternLevel=1;newPattern()}
function patternToken(shape,color='#151515',rotation=0,size=1){return{shape,color,rotation,size}}
function tokenKey(t){return`${t.shape}|${t.color}|${t.rotation}|${t.size}`}
function tokenHTML(t,tag='span',extra='',attrs=''){return`<${tag} class="pattern-symbol ${extra}" ${attrs} style="color:${t.color};transform:rotate(${t.rotation}deg) scale(${t.size})">${t.shape}</${tag}>`}
function buildPattern(level){
  const length=level<=5?5+Math.floor(level/2):level<=10?7+Math.floor((level-6)/2):level<=15?8+Math.floor((level-11)/2):level<=20?9+Math.floor((level-16)/2):11+Math.floor((level-21)/2);
  const a=symbols[level%symbols.length],b=symbols[(level+2)%symbols.length],c=symbols[(level+4)%symbols.length];const seq=[];
  for(let i=0;i<length;i++){
    if(level<=5)seq.push(patternToken(i%2?a:b));
    else if(level<=10)seq.push(patternToken([a,b,c][i%3]));
    else if(level<=15)seq.push(patternToken(i%2?a:b,patternColors[i%3]));
    else if(level<=20)seq.push(patternToken([a,b,c][i%3],patternColors[i%2],(i%4)*45));
    else seq.push(patternToken([a,b,c][i%3],patternColors[(i*2)%patternColors.length],(i%4)*45,i%2?.78:1.05));
  }
  return seq;
}
function makeDistractor(answer,n){return patternToken(symbols[(symbols.indexOf(answer.shape)+n+1)%symbols.length],patternColors[(patternColors.indexOf(answer.color)+n+1+patternColors.length)%patternColors.length],(answer.rotation+(n+1)*45)%360,answer.size===1.05?.78:1.05)}
function newPattern(){const seq=buildPattern(patternLevel);patternAnswer=seq[seq.length-1];const shown=seq.slice(0,-1);const wrongCount=3,progress=patternLevel*4;patternOptions=patternLevel<=10?[patternAnswer,...Array.from({length:wrongCount},(_,i)=>patternToken(symbols[(symbols.indexOf(patternAnswer.shape)+i+1)%symbols.length]))]:[patternAnswer,...Array.from({length:wrongCount},(_,i)=>makeDistractor(patternAnswer,i))];patternOptions.sort(()=>Math.random()-.5);shell('Patterns grow longer and more complex, but only the final shape is missing.',`<div class="game-status"><h3>LEVEL ${patternLevel} / 25</h3><p>WHAT COMES NEXT?</p></div><div class="run-progress"><div class="run-progress-head"><span>LEVEL ${patternLevel}</span><b>${progress}% COMPLETE</b><span>LEVEL 25</span></div><div class="run-progress-track"><div class="run-progress-fill" style="--progress:${progress}%"></div></div></div><div class="pattern-sequence">${shown.map(x=>tokenHTML(x)).join('')}<span class="pattern-symbol missing">?</span></div><div class="pattern-options">${patternOptions.map((x,i)=>tokenHTML(x,'button','pattern-option-choice',`data-option="${i}"`)).join('')}</div>`);document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>checkPattern(+b.dataset.option))}
function checkPattern(choice){if(tokenKey(patternOptions[choice])===tokenKey(patternAnswer)){const completed=patternLevel;score+=completed*10;updateScore();if(completed>=25){setTimeout(()=>currentGame==='pattern'&&showVictory('PATTERN PULSE','You mastered all 25 visual patterns!'),400)}else{patternLevel++;setTimeout(()=>currentGame==='pattern'&&newPattern(),500)}}else{if(registerMistake())return;score=Math.max(0,score-5);updateScore();toast('LOOK AGAIN — CHECK EVERY PROPERTY')}}

loadRoute();
